Web-pack+JS
ok-technopolis-2020/Pletnev_Timofey pull request #4
Opened 2020-11-25 17:40 UTC by TiMaTiFeY

Ох... Чувствую, этот PR будет иметь over 100 комментариев))) Сделал как смог, время рефакторить.... Не бейте только xD

2020-11-26 14:15 UTC, fromanywhere requested changes

2020-11-26 14:15 UTC, fromanywhere commented on src/app/modules/actions-bar.js
> +        this.#counterLeft = document.querySelector('.task-counter__text');
давайте учиться делать выборки по js-классам. Идея в том, что рефакторить логику отдельно от верстки будет проще

2020-11-26 14:15 UTC, fromanywhere commented on src/app/modules/actions-bar.js
> +        this.#counterLeft.innerHTML = ++this.#count + " items left";
textContent безопаснее

2020-11-26 14:15 UTC, fromanywhere commented on src/app/modules/task.js
> +        this.#isRemoved = false;
а в чем идея хранить состояние удаления?

2020-11-26 14:15 UTC, fromanywhere commented on src/app/modules/task.js
> +            this.#spanItem.style.display = "flex";
ну нет, никаких модификаций стилей напрямую, только через стили

2020-11-26 14:15 UTC, fromanywhere commented on src/app/modules/task.js
> +        this.#checkBoxItem.addEventListener('click', () => { taskViewer.renderTasks() });
а удалять этот листенер как будем потом?

2020-11-26 14:15 UTC, fromanywhere commented on src/app/modules/tasksViewer.js
> +        if (this.#mode !== TasksViewer.#FILTER_COMPLETED) {
выглядит странным проверять в этом месте. Это же зона ответственности рендера

2020-11-26 14:15 UTC, fromanywhere commented on src/app/modules/tasksViewer.js
> +                } else i++;
ну нет, никаких опусканий скобок. Ну и вообще я бы посмотрел на работу с коллекциями — выглядит, что здесь tasks.filter().forEach()

2020-11-26 14:15 UTC, fromanywhere commented on src/app/modules/tasksViewer.js
> +export default tasksViewer;
никаких дефолтных экспортов

2020-11-26 14:16 UTC, fromanywhere commented on src/app/modules/actions-bar.js
> +        this.#counterLeft = document.querySelector('.task-counter__text');
типа, .js-task-counter__text'

2020-11-26 16:47 UTC, TiMaTiFeY commented on src/app/modules/actions-bar.js
> +        this.#counterLeft = document.querySelector('.task-counter__text');
Не совсем понимаю если честно. Тогда в HTML этот `span` будет иметь селектор `.js-task-counter-text` ? Т.е. это только для того, что когда мы смотри HTML код, то понимаем, что этот блок будет меняться с помощью JavaScript? Или как

2020-11-26 16:49 UTC, TiMaTiFeY commented on src/app/modules/task.js
> +        this.#isRemoved = false;
Чтобы в `taskViewer` из массива `tasks` удалять. Просто не могу придумать, как к кнопке привязать `eventListener`, чтобы по ее нажатию, этот `task` удалялся из массива.

2020-11-26 16:52 UTC, TiMaTiFeY commented on src/app/modules/task.js
> +            this.#spanItem.style.display = "flex";
А как тогда реализовать смену режима просмотра и редактирования текста таска? Вроде как даже когда мы проходили HTML на занятиях и этот вопрос поднимали. Вы вроде говорили, что смена режимов будет с помощью JavaScript.

2020-11-27 10:28 UTC, fromanywhere commented on src/app/modules/actions-bar.js
> +        this.#counterLeft = document.querySelector('.task-counter__text');
да, всё верно. Это делается для того, чтобы при изменениях макетов структуру дерева и какие-то декоративные вещи можно было дешевле изменить, не оторвав логику

2020-11-27 10:39 UTC, fromanywhere commented on src/app/modules/task.js
> +        this.#isRemoved = false;
а вот в этом месте имеет смысл пойти почитать про mvc с активной моделью. Вообще об этом будет лекция в течение недели-двух, но лучше, наверное, заранее. 

Как минимум имеет смысл подумать о том, что вот есть отдельно модель, которая хранит какие-то данные, есть вью, которые суть есть наши компоненты, которые отвечают за рендер, и есть контроллер, который занимается изменением модели от пользовательских действий. 

Тогда оказывается, что все обработчики addEventListener/removeEventListener всегда оказываются в классах, которые отвечают за view, и функции-обработчики — это методы контроллера. А контроллер внутри себя удаляет/добавляет/меняет что-то в массиве

А ререндер компонентов происходит по факту изменения массива автоматически, по шаблону «Наблюдатель», то это уже совсем другая история

2020-12-21 10:12 UTC, fromanywhere requested changes
Есть тема получить 5 за незначительные правки

2020-12-21 10:12 UTC, fromanywhere commented on src/app/modules/task.js
> +            this.#spanItem.style.display = "flex";
Все еще

2020-12-21 10:12 UTC, fromanywhere commented on src/app/modules/actions-bar.js
> +        this.#counterLeft = document.querySelector('.task-counter__text');
Всё еще

2020-12-21 10:12 UTC, fromanywhere commented on src/app/modules/tasksViewer.js
> +        this.#ul = document.getElementById("list");
Это что за сквозная выборка

2020-12-21 17:50 UTC, fromanywhere approved these changes
окей

2020-12-21 17:50 UTC, fromanywhere commented on src/app/modules/tasksViewer.js
> +            this.#tasks[i].setCompleted = true;
не понял, зачем тут сетать, если ниже сетается

2020-12-21 17:53 UTC, TiMaTiFeY commented on src/app/modules/tasksViewer.js
> +            this.#tasks[i].setCompleted = true;
Косяк, исправил :)

2020-12-21 18:00 UTC, merged